name: Trigger Vercel Redeploy on Profile Update

on:
  # Runs when you push changes (optional)
  push:
    branches: [ main ]

  # Runs periodically to check for profile updates (every 6 hours here)
  schedule:
    - cron: "0 */72 * * *"

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel Deploy Hook
        run: |
          curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
